@startuml
left to right direction

package "pirates_of_paradigms" {
    package "tiles" {
        interface ITile
        interface ITileContent
        abstract AbstractTile <<package>> implements ITile
        class BlueSeaTile extends AbstractTile
        class StormTile extends AbstractTile
        class PortTile extends AbstractTile
        class MistTile extends AbstractTile
        class ReefTile extends AbstractTile
        class SeaCurrentTile extends AbstractTile
        class IslandTile extends AbstractTile
        ITileContent <. ITile : 'uses'
    }

    package "treasures" {
        interface ITreasure implements pirates_of_paradigms.tiles.ITileContent
        class Resource implements ITreasure
        class DynasticTreasure implements ITreasure
    }

    package "ship" {
        class Ship implements pirates_of_paradigms.tiles.ITileContent
    }
}

' ################################################################
' Esta sección es para definir miembros y metodos
' ################################################################

interface pirates_of_paradigms.tiles.ITile {
    + {abstract} isNavigable(): bool
    + {abstract} getContent(): ITileContent
    + {abstract} setContent(content: ITileContent): void
}

interface pirates_of_paradigms.tiles.ITileContent {
    + {abstract} getName(): String
    + {abstract} blocksNavigation(): bool
}

abstract pirates_of_paradigms.tiles.AbstractTile {
    - content: ITileContent
    + getContent(): ITileContent
    + setContent(content: ITileContent): void
}

interface pirates_of_paradigms.treasures.ITreasure {
    + {abstract} onCollect(ship: Ship): void
}

class pirates_of_paradigms.treasures.Resource {
    - name: String
    - gold: int
    - wood: int
}

class pirates_of_paradigms.treasures.DynasticTreasure {
    owner: Fleet
}

class pirates_of_paradigms.ship.Ship {
    - fleet: Fleet
    - kind: String
    - name: String
    - healthPoints: int
    - attack: int
    - defense: int
    - moves: int
    - range: int
}

@enduml